### PR TITLE
Add livestream cache

### PR DESCRIPTION
**Pull request by mediaminister**
This includes:
- Add livestream cache for faster zapping

### CODE REVIEW

**Comment by michaelarnauts** [comment]
How much improvement does this do? I'm thinking to also cache the livestream tokens and URL to improve the playback of live TV on VTM Go, but from a quick look, it seems the most delay is due to the buffering in IA.

Maybe it's not worth the effort?

**Comment by mediaminister** [comment]
It saves at least one http request after the user has clicked. I tested this and this can decrease the zapping delay with 490 ms.
Considering the zapping experience users had in the analog TV era, every 100 milliseconds you can gain is a noticeable improvement.

**Comment by michaelarnauts** [comment]
> It saves at least one http request after the user has clicked. I tested this and this can decrease the zapping delay with 490 ms.
> Considering the instant zapping experience users had in the analog TV era, every 100 milliseconds you can gain is a noticeable improvement.

That's actually quite good! 👍

**Comment by mediaminister** [comment]
Yes, http response time is still quite slow, this is documented: https://www.littledata.io/average/server-response-time

**Pull request merged**
