### PR TITLE
Add product placement and kijkwijzer metadata

### LINKED ISSUE #816: Implement ageGroup and productPlacement support
### Describe the feature ###
Since some time VRT NU supports `ageGroup` and `productPlacement` in metadata, we could add support for this in Kodi.

And at some point also filter for this as part of parental advisory.

### PR DESCRIPTION
**Pull request by mediaminister**
This adds the kijkwijzer string to the mpaa Listitem infoLabel and adds PP and kijkwijzer string to the plot Listitem infoLabel.

This fixes #816

### CODE REVIEW

**Comment by dagwieers** [comment]
In VTM GO we use a metadata field used for this IIRC.

**Comment by mediaminister** [comment]
Indeed, the `mpaa` field and this PR adds the kijkwijzer string to this field. Do I need to add product placement also?

**Comment by dagwieers** [comment]
> Indeed, the `mpaa` field and this PR adds the kijkwijzer string to this field. Do I need to add product placement also?

Ah yes, it was the mpaa `field` ;-) I haven't tested it, but let's merge so I can test it together with the new library support.
I think our next release will become v2.5.0 packed with new features !

**Comment by dagwieers** [comment]
It is unfortunate my PR to add more metadata to the Information pane and studio icons to all views was never backported to Leia :-(
I patched my systeùs manually and it gives a much better user-experience IMO.

**Pull request merged**
