### PR TITLE
Add support for playing from the Guide with IPTV Manager

### PR DESCRIPTION
**Pull request by michaelarnauts**
This PR adds support to play programs from the PVR Guide through IPTV Manager.

Needs https://github.com/add-ons/service.iptv.manager/pull/19

### CODE REVIEW

**Comment by michaelarnauts** [comment]
I don't know of an elegant way to not pass the `vod` field if the channel has no guide.

**Comment by mediaminister** [comment]
With the dictionary update method?
```python



    @via_socket
    def send_channels():  # pylint: disable=no-method-argument
        """Return JSON-M3U formatted information to IPTV Manager"""
        streams = []
        for channel in CHANNELS:
            if not channel.get('live_stream_id'):
                continue
            stream = dict(
                id=channel.get('epg_id'),
                name=channel.get('label'),
                logo=channel.get('logo'),
                preset=channel.get('preset'),
                stream='plugin://plugin.video.vrt.nu/play/id/{live_stream_id}'.format(**channel),
            )
            if channel.get('has_tvguide'):
                stream.update(dict(vod='plugin://plugin.video.vrt.nu/play/airdate/{name}/{{date}}'.format(**channel)))

            streams.append(stream)
        return dict(version=1, streams=streams)
```

**Comment by michaelarnauts** [comment]
> With the dictionary update method?

I was thinking in the lines as this, but I don't consider this an improvement actually.

```python
    @via_socket
    def send_channels():  # pylint: disable=no-method-argument
        """Return JSON-M3U formatted information to IPTV Manager"""
        streams = []
        for channel in CHANNELS:
            if not channel.get('live_stream_id'):
                continue
            streams.append(dict(
                id=channel.get('epg_id'),
                name=channel.get('label'),
                logo=channel.get('logo'),
                preset=channel.get('preset'),
                stream='plugin://plugin.video.vrt.nu/play/id/{live_stream_id}'.format(**channel),
            ).update(dict(
                vod='plugin://plugin.video.vrt.nu/play/airdate/{name}/{{date}}'.format(**channel),
            ) if channel.get('has_tvguide') else dict()))
        return dict(version=1, streams=streams)
```

I guess it could also be done with something like `dict(**dict(id=...,name=...), **(dict(vod=...) if channel.get('has_tvguide') else dict())` but I'll stick with the normal readable way.

**Comment by dagwieers** [comment]
In fact, the `dict.update()` method accepts kwargs !

So this will work as well:
```python
            if channel.get('has_tvguide'):
                item.update(vod='plugin://plugin.video.vrt.nu/play/airdate/{name}/{{date}}'.format(**channel))
```

**Comment by dagwieers** [comment]
Or we could allow a null value to indicate there is no VOD, next to not having the vod-key.
I think that would be a good practice anyway.

**Comment by michaelarnauts** [comment]
The field is optional, and null values are interpreted as no vod, it was mainly just esthetics of not sending an empty vod line.

**Comment by dagwieers** [comment]
Let's merge this. We can fix or improve later.

**Pull request merged**
