### PR TITLE
Various backports

### PR DESCRIPTION
**Pull request by dagwieers**
This PR includes:
- A fix to multizip in Makefile for Bash
- Implement Kodi v19 xbmcvfs.translatePath() support
- Various improvements to the xbmc stubs

### CODE REVIEW

**Review by mediaminister — COMMENTED** [review]
`make zip` and `make multizip` is failing
```
test@pc:~/plugin.video.vrt.nu$ make multizip
-e = Cleaning up
find . -name '*.py[cod]' -type f -delete
find . -name '__pycache__' -type d -delete
rm -rf .pytest_cache/ .tox/
rm -f *.log tests/userdata/tokens/*.tkn
addon.xml:2: parser error : Start tag expected, '<' not found

^
addon.xml:2: parser error : Start tag expected, '<' not found

^
addon.xml:2: parser error : Start tag expected, '<' not found

^
addon.xml:2: parser error : Start tag expected, '<' not found

^
addon.xml:2: parser error : Start tag expected, '<' not found

^
addon.xml:2: parser error : Start tag expected, '<' not found

^
make[1]: Entering directory '/home/test/plugin.video.vrt.nu'
-e = Cleaning up
find . -name '*.py[cod]' -type f -delete
find . -name '__pycache__' -type d -delete
rm -rf .pytest_cache/ .tox/
rm -f *.log tests/userdata/tokens/*.tkn
addon.xml:2: parser error : Start tag expected, '<' not found

^
addon.xml:2: parser error : Start tag expected, '<' not found

^
addon.xml:2: parser error : Start tag expected, '<' not found

^
addon.xml:2: parser error : Start tag expected, '<' not found

^
addon.xml:2: parser error : Start tag expected, '<' not found

^
addon.xml:2: parser error : Start tag expected, '<' not found

^
addon.xml:2: parser error : Start tag expected, '<' not found

^
-e = Building new package
cd ..; zip -r --kodiutils-backports-59c54de.zip /addon.xml /channels.m3u8 /LICENSE /README.md /resources/ -x \*.new \*.orig \*.pyc \*.pyo

zip error: Invalid command arguments (long option 'kodiutils-backports-59c54de.zip' not supported)
Makefile:80: recipe for target 'build' failed
make[1]: *** [build] Error 16
make[1]: Leaving directory '/home/test/plugin.video.vrt.nu'
addon.xml:2: parser error : Start tag expected, '<' not found

^
addon.xml:2: parser error : Start tag expected, '<' not found

^
make[1]: Entering directory '/home/test/plugin.video.vrt.nu'
-e = Cleaning up
find . -name '*.py[cod]' -type f -delete
find . -name '__pycache__' -type d -delete
rm -rf .pytest_cache/ .tox/
rm -f *.log tests/userdata/tokens/*.tkn
addon.xml:2: parser error : Start tag expected, '<' not found

^
addon.xml:2: parser error : Start tag expected, '<' not found

^
addon.xml:2: parser error : Start tag expected, '<' not found

^
addon.xml:2: parser error : Start tag expected, '<' not found

^
addon.xml:2: parser error : Start tag expected, '<' not found

^
addon.xml:2: parser error : Start tag expected, '<' not found

^
addon.xml:2: parser error : Start tag expected, '<' not found

^
-e = Building new package
cd ..; zip -r --kodiutils-backports-59c54de.zip /addon.xml /channels.m3u8 /LICENSE /README.md /resources/ -x \*.new \*.orig \*.pyc \*.pyo

zip error: Invalid command arguments (long option 'kodiutils-backports-59c54de.zip' not supported)
Makefile:80: recipe for target 'build' failed
make[1]: *** [build] Error 16
make[1]: Leaving directory '/home/test/plugin.video.vrt.nu'
Makefile:86: recipe for target 'multizip' failed
make: [multizip] Error 2 (ignored)
```

**Comment by dagwieers** [comment]
On what environment is this? I tried both Bash and busybox sh

Without `-e` it is failing on both. Maybe we should move to `printf` which is more portable anyway, I will look into that.

**Comment by mediaminister** [comment]
Gewoon Linux Mint 19.3 Tricia:
GNU bash, version 4.4.20(1)-release (x86_64-pc-linux-gnu)
Linux 5.4.0-58-generic #64~18.04.1-Ubuntu SMP Wed Dec 9 17:11:11 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Review by mediaminister — APPROVED** [review]
You can merge this, everything works now.

**Comment by dagwieers** [comment]
That is really strange, as I would be expecting Bash to support the `-e` flag (even if it was just for backward compatbility).
Anyhow, `printf` is clearly the way to go. We may want to fix some of these changes to other add-ons as well.

But @michaelarnauts has been making nice advances in testing pipelines too, so I think we should make VRT NU exemplary first, and then retrofit other projects with these fixes.

**Comment by mediaminister** [comment]
I guess it's because the echo command was in a foreach function.

**Pull request merged**
